apiVersion: hyperdhcp.blahonga.me/v1beta1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: hyperdhcp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hyperdhcp
  name: server-sample
spec:
  dhcpConfig:
    # DHCP server identifier (typically the IP of the server)
    serverID: "192.168.1.1"
    # DNS servers to provide to clients
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    # Default gateway/router
    router: "192.168.1.1"
    # Subnet mask
    subnetMask: "255.255.255.0"
    # IP address range to lease
    range:
      start: "192.168.1.100"
      end: "192.168.1.200"
      leaseTime: "1h"
  networkAttachment:
    # Name of the Multus network attachment definition
    name: "dhcp-net"
    # Namespace where the network attachment definition exists
    namespace: "default"
    # IP addresses to bind the DHCP server to (one per interface)
    ips:
      - "192.168.1.1"
